name: linette
description: 'Plan to save the world'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  flutter_launcher_icons: '0.14.4'
  flutter_native_splash: '2.4.7'

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: 'assets/icon/light/icon.png'
  adaptive_icon_foreground: 'assets/icon/light/icon.png'
  adaptive_icon_background: '#f2f2f2'

flutter_native_splash:
  android: true
  image: 'assets/icon/light/icon.png'
  image_dark: 'assets/icon/dark/icon.png'
  branding: 'assets/branding/light/branding.png'
  branding_dark: 'assets/branding/dark/branding.png'
  color: '#f2f2f2'
  color_dark: '#070707'
  android_12:
    image: 'assets/icon/light/icon.png'
    image_dark: 'assets/icon/dark/icon.png'
    branding: 'assets/branding/light/branding.png'
    branding_dark: 'assets/branding/dark/branding.png'
    icon_background_color: '#f2f2f2'
    icon_background_color_dark: '#070707'